****************************************************************************************;
*     There are 3 programs to analyze the salmon and shellfish permit databases:       *;
*         1. permits.sas                                                               *;
*         2. harvest.sas                                                               *;
*         3. estimates.sas                                                             *;
*     This program reads and modifies data for harvest                                 *;
*     This program is stored as h:\common\pat\permits\SHRIMP\2013\harvest.sas          *;
****************************************************************************************;
dm 'keydef f12 "output ;clear ; log ; clear ;"';
dm "output;clear;log;clear";
proc datasets library = work kill; run;

%LET PROJECT = SHRIMP;
/*%LET DATA = pwshvc_2020;*/
%LET YEAR = 2021;
%LET PROGRAM = HARVEST;
%LET SP = SHRIMP;

OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
OPTION VALIDVARNAME=UPCASE;
LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";

TITLE1 "&PROJECT - &YEAR";

**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;

* Import the harvest changes that Jay made here;
PROC IMPORT OUT= WORK.HARVEST 
 DATAFILE= "O:\DSF\RTS\common\Pat\Permits\Shrimp\&year\PWSHVC_&year._JAB.xlsx"  
	DBMS=xlsx REPLACE;
     SHEET = "PWS";
RUN;

PROC PRINT DATA = HARVEST (OBS = 20);
RUN;

DATA HARVEST_1; 
	SET HARVEST;
     LOCATION = UPCASE(LOCATION);
     IF SOAKTIME = 0 THEN SOAKTIME = .;
     IF POTS = 0 THEN POTS = .;
	 IF SHRIMP GT 0 THEN NOCATCH = 0;
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
	 IF LOCATION = '' THEN LOCATION = "UNKNOWN";
     RENAME PERMITNO = PERMIT;
	 MONTH = MONTH(HARVDATE);
	 DAY = DAY(HARVDATE);
     DROP NOCATCH NOHRVRPT COMMENTS;
RUN;

PROC PRINT DATA = HARVEST_1 (OBS = 30);
RUN;

* JAYS EDITS;

PROC SORT DATA = HARVEST_1; BY HVRECID; run;

/*DATA HARVEST; MERGE HARVEST HARVEST_CHANGE; BY HVRECID;*/
/*     IF NEW_COMMENT NE '' THEN DO; COMMENTS = NEW_COMMENT; END;*/
/*     IF NEW_POTS NE . THEN DO; POTS = NEW_POTS; END;*/
/*     IF NEW_SHRIMP NE . THEN DO; SHRIMP = NEW_SHRIMP; END;*/
/*     IF NEW_SOAKTIME NE . THEN DO; SOAKTIME = NEW_SOAKTIME; END;*/
/*	 IF LOCATION = '' THEN LOCATION = "UNKNOWN";*/
/*	 LOCATION = UPCASE(LOCATION);*/
/*	 DROP COMMENTS NEW_COMMENT NEW_POTS NEW_SHRIMP NEW_SOAKTIME MONTH CATCH HRVRPT DAY;*/
/*RUN;*/

PROC PRINT DATA = HARVEST_1 (OBS = 20);
RUN;



PROC IMPORT OUT= WORK.CORRECT_STATAREA 
DATAFILE= "O:\DSF\RTS\common\Pat\Permits\Shrimp\2020\2020_locations"  
DBMS=xlsx REPLACE;
     SHEET = "2020_locations_amended";
RUN;

*\ SAS FILE EDITED BY BUZZEE 2020, TO READ LOCATION FILE IN FROM EXCEL INSTEAD OF AS SASDATA*\
*GET THE CORRECTED STAT AREAS;
*\ LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT";
*\DATA CORRECT_STATAREA; SET SASDATA.LOCATION_STATAREA;
*\PROC SORT DATA = CORRECT_STATAREA; BY LOCATION STATAREA;
*\PROC PRINT;
*\RUN;

DATA WORK.CORRECT_STATAREA;
	SET WORK.CORRECT_STATAREA;
	LOCATION = UPCASE(LOCATION);
RUN;

*Problem Merging these two datasets *;
PROC SORT DATA = CORRECT_STATAREA; BY LOCATION STAT_AREA;
PROC PRINT DATA = CORRECT_STATAREA (OBS = 30);
RUN;

PROC SORT DATA = HARVEST; BY LOCATION;
PROC PRINT DATA = HARVEST (OBS = 10);

DATA HARVEST; MERGE HARVEST CORRECT_STATAREA;
	BY LOCATION;
    IF PERMIT = . THEN DELETE;
RUN;


PROC PRINT DATA = HARVEST (OBS = 50);
RUN;

DATA LOC_PROBLEMS; SET HARVEST;
     IF STAT_AREA = .;
PROC PRINT DATA = LOC_PROBLEMS;
RUN;



PROC FREQ DATA = LOC_PROBLEMS;
     TABLES LOCATION / OUT=CHECK NOPRINT;
PROC PRINT DATA = CHECK;
RUN;


PROC EXPORT DATA= WORK.CHECK
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\SHRIMP PERMITS &YEAR" DBMS=XLSX REPLACE;
            SHEET="LOCATION PROBLEMS"; 
RUN;


LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\common\PERMITS\&PROJECT\&YEAR";


* GOOD UNTIL HERE 3/10/20 DIV BY ZERO ERROR*;

DATA HARVEST; SET HARVEST;
     GALLONS_PER_POT = ROUND(SHRIMP/POTS,0.5);  FORMAT GALLONS_PER_POT 4.1;
     POT_DAYS = POTS * (SOAKTIME/24); FORMAT POT_DAYS 8.1;

PROC SORT DATA = HARVEST; BY PERMIT;
PROC PRINT DATA = HARVEST (OBS = 40);
     TITLE2 'HARVEST FILE';
     TITLE3 ;
RUN;


DATA HARVEST; SET HARVEST;
   * IF GALLONS_PER_POT GT 2.4 THEN SHRIMP = SHRIMP/120;
     GALLONS_PER_POT = ROUND(SHRIMP/POTS,0.5);  FORMAT GALLONS_PER_POT 4.1;
     WEEK = INTCK('WEEK',INTNX('YEAR', HARVDATE, 0), HARVDATE) + 1;
RUN;


PROC FREQ DATA = HARVEST;
     TABLES CATCH HRVRPT HARVDATE SHRIMP POTS SOAKTIME GALLONS_PER_POT LOCATION STAT_AREA POT_DAYS WEEK;
     TITLE2 'SUMMARIES FROM HARVEST FILE';

PROC FREQ DATA = HARVEST;
     WHERE STAT_AREA = .;
	 TABLES LOCATION;
     TITLE2 'THESE LOCATIONS DO NOT HAVE A STATAREA';
RUN;


PROC FREQ DATA = HARVEST;
     TITLE2 'REPORTED HARVEST';
     TABLES SHRIMP / NOPRINT OUT = FREQ_HARVEST;
RUN;


PROC FREQ DATA = HARVEST;
     TITLE2 'REPORTED HARVEST BY STATAREA';
     TABLES STAT_AREA / OUT = HARVEST_BY_AREA;
     WEIGHT SHRIMP;
RUN;

PROC FREQ DATA = HARVEST;
     TITLE2 'REPORTED HARVEST BY WEEK';
     TABLES WEEK / NOPRINT OUT = HARVEST_BY_WEEK;
     WEIGHT SHRIMP;
RUN;

PROC FREQ DATA = HARVEST;
     TITLE2 'REPORTED EFFORT BY STATAREA';
     TABLES STAT_AREA / NOPRINT OUT = EFFORT_BY_AREA;
     WEIGHT POT_DAYS;
RUN;

PROC FREQ DATA = HARVEST;
     TITLE2 'REPORTED EFFORT BY WEEK';
     TABLES WEEK / NOPRINT OUT = EFFORT_BY_WEEK;
     WEIGHT POT_DAYS;
RUN;


PROC PRINT DATA = HARVEST;
     WHERE GALLONS_PER_POT GT 2.4;
     TITLE2 'HARVEST FILE';
     TITLE3 'GALLONS PER POT GT 2.4';
	 RUN;
/*
PROC PRINT DATA = HARVEST;
     WHERE POTS GT 5;
     TITLE3 'MORE THAN 5 POTS';
*/
PROC PRINT DATA = HARVEST;
     WHERE SOAKTIME GT 400;
     TITLE3 'SOAK TIME GREATER THAN 400';
RUN;




DATA HARVEST_BY_AREA; SET HARVEST_BY_AREA;
     RENAME COUNT = SHRIMP PERCENT = PERCENT_HARVEST;
DATA EFFORT_BY_AREA; SET EFFORT_BY_AREA;
     RENAME COUNT = POT_DAYS PERCENT = PERCENT_EFFORT;

DATA HARVEST_BY_WEEK; SET HARVEST_BY_WEEK;
     RENAME COUNT = SHRIMP PERCENT = PERCENT_HARVEST;     
DATA EFFORT_BY_WEEK; SET EFFORT_BY_WEEK;
     RENAME COUNT = POT_DAYS PERCENT = PERCENT_EFFORT;   

RUN;


DATA TABLE_STAT_AREA; MERGE HARVEST_BY_AREA EFFORT_BY_AREA; BY STAT_AREA;
     IF SHRIMP = . THEN SHRIMP = 0;
	 IF STAT_AREA NE . AND PERCENT_HARVEST = . THEN PERCENT_HARVEST = 0;
PROC PRINT;
     TITLE3 'EFFORT AND HARVEST BY STATAREA';
RUN;

DATA TABLE_WEEK; MERGE HARVEST_BY_WEEK EFFORT_BY_WEEK; BY WEEK;
PROC PRINT;
     TITLE3 'EFFORT AND HARVEST BY WEEK';
RUN;


PROC MEANS NOPRINT DATA = HARVEST; 
     VAR GALLONS_PER_POT SHRIMP POT_DAYS;
     OUTPUT OUT = SUMMARY MEAN(GALLONS_PER_POT) = MEAN_GALLONS_PER_POT SUM = JUNK TOTAL_SHRIMP TOTAL_POT_DAYS;
RUN;

DATA SUMMARY; SET SUMMARY;
     RENAME _FREQ_ = RECORDS;
     DROP JUNK _TYPE_;
PROC PRINT;
     TITLE2 'SUMMARY OF REPORTED INFORMATION';
RUN;


PROC SORT DATA = HARVEST; BY STAT_AREA;
PROC MEANS NOPRINT DATA = HARVEST; BY STAT_AREA;
     VAR GALLONS_PER_POT SHRIMP POT_DAYS;
     OUTPUT OUT = SUMMARY MEAN(GALLONS_PER_POT) = MEAN_GALLONS_PER_POT SUM = JUNK TOTAL_SHRIMP TOTAL_POT_DAYS;
RUN;

DATA SUMMARY; SET SUMMARY;
     RENAME _FREQ_ = RECORDS;
     DROP JUNK _TYPE_;
PROC PRINT;
     TITLE2 'SUMMARY OF REPORTED INFORMATION';
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
DATA SASDATA.SHRIMP_HARVEST; SET HARVEST; 
RUN;


DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
     KEEP PERMITNO HVRECID COMMENTS SHRIMP;
RUN;

PROC EXPORT DATA= WORK.COMMENTS
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\SHRIMP PERMITS &YEAR" DBMS=XLSX REPLACE;
            SHEET="HARVEST COMMENTS"; 
RUN;


*PROC EXPORT DATA= WORK.HARVEST
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\SHRIMP PERMITS &YEAR" DBMS=XLSX REPLACE;
 *           SHEET="HARVEST RECORDS"; 
*RUN;

PROC EXPORT DATA= WORK.TABLE_STAT_AREA
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\SHRIMP PERMITS &YEAR" DBMS=XLSX REPLACE;
            SHEET="EFFORT AND HARVEST BY STATAREA"; 
RUN;

PROC EXPORT DATA= WORK.TABLE_WEEK
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\SHRIMP PERMITS &YEAR" DBMS=XLSX REPLACE;
            SHEET="EFFORT AND HARVEST BY WEEK"; 
RUN;


